### ISSUE TITLE
Question about `age`

### ISSUE THREAD

**Issue by armenr** [lucj/argocd-helmfile-plugin#2]
Howdy - 

Thanks for the work you've done on this, and for sharing it with the community. 

I wanted to ask one clarifying question: is `age` a *requirement* here, or just something useful that's been included as part of a recommended/typical workflow?

Thanks!
_Armen

**Comment by lucj** [comment]
Hello @armenr 
Sorry I was probably too quick when talking about age usage. I'll add an example in the README.
Basically, Helmfile can use secrets.yaml file encrypted with SOPS (age is one of the encryption method that SOPS can use). So the idea is to create an age private key file that we (as admin) can use to encrypt data and provide that age key to ArgoCD so it can decrypt the data when it deploys / updates an application.
age is not a requirement here, I would not say it's a recommendation but mostly a handy tool that can easily be used for that encryption / decryption purpose.
You can find some more info here: https://helmfile.readthedocs.io/en/latest/#environment-secrets
Does that help ?

**Comment by lucj** [comment]
@armenr, can this help a bit: https://github.com/lucj/argocd-helmfile-plugin#about-secret-encryption ?

**Comment by lucj** [comment]
Hi @armenr, just a quick follow up. Did the added part on age help ?

**Comment by armenr** [comment]
@lucj - Yessir, that helped a lot. I was just unaware of `age` as being a tool (I've been living under a rock, rebuilding a whole infra + platform eng on top + CI/CD automation)...But I get it now, and thank you for the clarification.

As a "new user" or consumer of your plugin, it's helpful to know whether I *have* to use a certain thing or not...especially when that thing is new/unfamiliar to me.

So, that definitely helped. Thank you! :)

**Comment by lucj** [comment]
Thanks a lot @armenr, I'm glad this could help.
