### ISSUE TITLE
update DockerHub image

### ISSUE THREAD

**Issue by derlin** [lucj/argocd-helmfile-plugin#6]
Hello there! I see you add support for namespaces, but the latest Docker image (`0.0.10`) doesn't reflect this change. Can you create a new Docker release? It would be awesome :)

Thanks!

**Comment by lucj** [comment]
Thanks @derlin I'll check that. Also, feel free to create a PR :)

**Comment by derlin** [comment]
Well, I didn't see any ci to deploy to docker hub, so I am not sure how a PR would help. Thank you!

**Comment by lucj** [comment]
no problem, I just need to figure out what needs to be changed in the image :)

**Comment by derlin** [comment]
If this can help you, I am talking of those changes you did in the plugin.yaml: https://github.com/lucj/argocd-helmfile-plugin/commit/a1083aaf3d5b5e1a311b2dbab64c650382cf7583. They are not present on the latest image in the dockerhub

**Comment by lucj** [comment]
My bad, I've accepted a PR some time ago but never released the image. I'll do it soon and also make sure to add a proper CI. Sorry for this.

**Comment by lucj** [comment]
I've published the image 0.0.11 taking into account the changes done in PR #5 .
Please let me know if this is ok for you.

**Comment by derlin** [comment]
Works like a charm, thanks!
